### ISSUE TITLE
gdal2tiles.py doesn't work

### ISSUE THREAD

**Issue by olivierdalang** [andrejreznik/docker-python-gdal#11]
Hi !

It seems gdal2tiles.py (and other scripts) are installed, but for some reason, running `gdal2tiles.py --help` returns this error :
```
$> gdal2tiles.py test.tifTraceback (most recent call last):
  File "/usr/local/bin/gdal2tiles.py", line 4, in <module>
    __import__('pkg_resources').run_script('GDAL==3.0.0', 'gdal2tiles.py')
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/gdal2tiles.py' not found in metadata at '/usr/local/lib/python3.7/site-packages/GDAL-3.0.0-py3.7.egg-info'
```

The script works well when ran from site-packages directly:
```
$> /usr/local/lib/python3.7/site-packages/GDAL-3.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/gdal2tiles.py test.tif
Generating Base Tiles:
0...10...
....
```

Not really sure why this is happening...

Cheers !

**Comment by andrejreznik** [comment]
On Sun, Jun 23, 2019 at 5:34 PM olivierdalang <notifications@github.com>
wrote:

> Hi !
>
> It seems gdal2tiles.py (and other scripts) are installed, but for some
> reason, running gdal2tiles.py --help returns this error :
>
> $> gdal2tiles.py test.tifTraceback (most recent call last):
>   File "/usr/local/bin/gdal2tiles.py", line 4, in <module>
>     __import__('pkg_resources').run_script('GDAL==3.0.0', 'gdal2tiles.py')
>   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
>     .format(**locals()),
> pkg_resources.ResolutionError: Script 'scripts/gdal2tiles.py' not found in metadata at '/usr/local/lib/python3.7/site-packages/GDAL-3.0.0-py3.7.egg-info'
>
> The script works well when ran from site-packages directly:
>
> $> /usr/local/lib/python3.7/site-packages/GDAL-3.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/gdal2tiles.py test.tif
> Generating Base Tiles:
> 0...10...
> ....
>
> Not really sure why this is happening...
>
> Cheers !
>

Hello, ﻿Olivier!
Thx for your ticket!

I will do some investigation of this issue in a few days.
I'm not sure that is a problem was in previous versions.
Also, I want to write some tests to make a safer version upgrade in the
future.

Anyway, if you found better or faster or just another solution feel free to
open PR :)

**Comment by andrejreznik** [comment]
Fixed
